name: "build cache"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0       ## not shallow
        filter: 'blob:none'  ## but blob-less
        submodules: true
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_url: https://releases.nixos.org/nix/nix-2.28.1/install
        extra_nix_config: |
          experimental-features = nix-command flakes fetch-closure configurable-impure-env
          impure-env = GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          trusted-users = root runner @wheel
    - uses: cachix/cachix-action@v12
      with:
        name: chezbryan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix config show
    - run: nix build --dry-run
    - run: nix build

    - name: build & sign darwin .apps
      if: startsWith(matrix.os, 'macos')
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        # BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        # PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        # echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        # mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        # cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

        # run the actual build
        ./darwin/build.sh
