name: "build cache"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0       ## not shallow
        filter: 'blob:none'  ## but blob-less
        submodules: true
    - name: reconstruct submodules as standalone repositories
      run: |
        git submodule foreach 'rm -f .git && mv ../.git/modules/$name .git'
        git submodule foreach 'sed -i /worktree/d .git/config'
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://releases.nixos.org/nix/nix-2.23.3/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - uses: cachix/cachix-action@v12
      with:
        name: chezbryan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --dry-run
    - run: nix build
